/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/auth/login': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Login with email and password
		 * @description Authenticates credentials, starts a one-step session and sets its cookie. A session the browser still holds is replaced. `/session/verify` takes the session past its second step.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['LoginRequest']
				}
			}
			responses: {
				/** @description Login successful */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Session']
					}
				}
				/** @description Invalid credentials */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Account inactive */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Too many wrong passwords for this email; try again in a minute */
				429: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/login/options': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** Start a passkey sign-in */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Authentication options */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['PasskeyOptions']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/login/passkey': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Login with a passkey
		 * @description Verifies the passkey against the challenge from `/login/options`, then starts a session like `/login`. A passkey is a second step in itself, so the session starts past it.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['PasskeyCredential']
				}
			}
			responses: {
				/** @description Login successful */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Session']
					}
				}
				/** @description Passkey not recognized */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Account inactive */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/logout': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Logout
		 * @description Deletes the current session and clears its cookie.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Logged out */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Message']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/session': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get current session
		 * @description Returns the current session and its user, or 401.
		 */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Active session */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Session']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/activity': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get recent activity
		 * @description Returns the latest activity on the signed-in user's account, newest first: sign-ins, changes to how they sign in, and what admins did.
		 */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Recent activity */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['ActivityList']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/sessions': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		/**
		 * Sign out other devices
		 * @description Deletes every session of the current user except this one.
		 */
		delete: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Other sessions deleted */
				204: {
					headers: {
						[name: string]: unknown
					}
					content?: never
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/session/verify/options': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Start a passkey second step
		 * @description Returns passkey options that name the passkeys of the signed-in user.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Authentication options */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['PasskeyOptions']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/session/verify': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Pass the second step
		 * @description Checks a passkey, authenticator code or recovery code of the signed-in user and marks the session as past its second step. The fifth wrong try ends the session. Past five wrong tries across all their sessions, a user gets one try every fifteen minutes.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['SecondFactorRequest']
				}
			}
			responses: {
				/** @description Session verified */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Session']
					}
				}
				/** @description Code or passkey not accepted, or no second factor */
				400: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Too many tries; the session ended */
				410: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Too many wrong tries for this user; try again in 15 minutes */
				429: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/register/options': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Get what the sign-up page needs */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Sign-up options */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['RegisterOptions']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/register': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Register a new account
		 * @description Creates an account and emails a link that verifies its address. When the email already has an account, emails its owner instead. Answers the same either way, so no one can learn who has an account. A network gets three sign-ups a day, counted either way.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['RegisterRequest']
				}
			}
			responses: {
				/** @description Check your email */
				202: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Message']
					}
				}
				/** @description Validation error, a failed Turnstile check, or a password known from a data breach */
				400: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Too many sign-ups from this network today */
				429: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/verify-email': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Email a verification link
		 * @description Emails the signed-in user a link that verifies their address, for 24 hours. A new link replaces the last one, at most once a minute.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Link sent */
				204: {
					headers: {
						[name: string]: unknown
					}
					content?: never
				}
				/** @description Unknown app origin */
				400: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Email already verified */
				409: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description A link was sent less than a minute ago */
				429: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/verify-email/confirm': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Verify an email
		 * @description Uses the token of a verification link and marks the email verified.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['VerifyEmailRequest']
				}
			}
			responses: {
				/** @description Email verified */
				204: {
					headers: {
						[name: string]: unknown
					}
					content?: never
				}
				/** @description Link expired or already used */
				400: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/reset-password': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Email a password reset link
		 * @description Emails a link that sets a new password, for one hour, when an active account has the email. Answers the same either way.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['ResetPasswordRequest']
				}
			}
			responses: {
				/** @description Link sent if the account exists */
				202: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Message']
					}
				}
				/** @description Unknown app origin */
				400: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/reset-password/confirm': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Set a new password
		 * @description Uses the token of a reset link to set a new password, marks the email verified, and ends every session of the user.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['NewPasswordRequest']
				}
			}
			responses: {
				/** @description Password set */
				204: {
					headers: {
						[name: string]: unknown
					}
					content?: never
				}
				/** @description Link expired or already used, or a password known from a data breach */
				400: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/passkeys': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** List your passkeys */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Your passkeys */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['PasskeyList']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		put?: never
		/**
		 * Add a passkey
		 * @description Verifies the new passkey against the challenge from `/options`.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['PasskeyCredential']
				}
			}
			responses: {
				/** @description Passkey added */
				201: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Passkey']
					}
				}
				/** @description Passkey could not be verified */
				400: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Sign in again */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/passkeys/options': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Start adding a passkey
		 * @description Needs a sign-in from the last ten minutes.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Registration options */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['PasskeyOptions']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Sign in again */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/passkeys/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		/**
		 * Remove a passkey
		 * @description Needs a sign-in from the last ten minutes. An admin keeps at least one.
		 */
		delete: {
			parameters: {
				query?: never
				header?: never
				path: {
					id: string
				}
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Passkey removed */
				204: {
					headers: {
						[name: string]: unknown
					}
					content?: never
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Sign in again */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Passkey not found */
				404: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Last passkey of an admin */
				409: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/mfa': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Show your second factors */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Your second factors */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Factors']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/mfa/totp/setup': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Start adding an authenticator app
		 * @description Needs a sign-in from the last ten minutes. The app stays off until `POST /totp` confirms a code; a new setup replaces an unconfirmed one.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Secret for the app */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['TotpSetup']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Sign in again */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description An authenticator app is already on */
				409: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Authenticator apps are not set up on this server */
				503: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/mfa/totp': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Turn on the authenticator app
		 * @description Needs a sign-in from the last ten minutes, and a code from the app.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['TotpConfirm']
				}
			}
			responses: {
				/** @description Authenticator app on */
				204: {
					headers: {
						[name: string]: unknown
					}
					content?: never
				}
				/** @description Code not correct */
				400: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Sign in again */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description No setup to confirm */
				404: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		/**
		 * Remove the authenticator app
		 * @description Needs a sign-in from the last ten minutes. An admin keeps a passkey or an authenticator app.
		 */
		delete: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Authenticator app removed */
				204: {
					headers: {
						[name: string]: unknown
					}
					content?: never
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Sign in again */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description No authenticator app */
				404: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Last second factor of an admin */
				409: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/mfa/recovery-codes': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Make new recovery codes
		 * @description Needs a sign-in from the last ten minutes and a second factor. Replaces any earlier codes.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description New recovery codes */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['RecoveryCodes']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Sign in again */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description No second factor */
				409: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/oauth/providers': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** List the sign-in providers */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description The providers set up on this server */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['OAuthProviders']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/oauth/identities': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** List your connected accounts */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Your connected accounts */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Identities']
					}
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/oauth/identities/{provider}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		/**
		 * Disconnect an account
		 * @description Needs a sign-in from the last ten minutes. Refuses when the user then has no password, no other connected account, and no passkey.
		 */
		delete: {
			parameters: {
				query?: never
				header?: never
				path: {
					provider: 'github' | 'google'
				}
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Account disconnected */
				204: {
					headers: {
						[name: string]: unknown
					}
					content?: never
				}
				/** @description Not authenticated */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Sign in again */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Not connected */
				404: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Last way to sign in */
				409: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/health': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Health check
		 * @description Returns the health status of the gateway and its database
		 */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Service is healthy or degraded */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['HealthResponse']
					}
				}
				/** @description Service is unhealthy */
				503: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['HealthResponse']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/users': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** List all users */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description List of users */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['UserList']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/users/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Get a user by ID */
		get: {
			parameters: {
				query?: never
				header?: never
				path: {
					/** @description Unique identifier (UUID) */
					id: string
				}
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description User found */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['User']
					}
				}
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		/**
		 * Deactivate or reactivate a user
		 * @description Deactivating signs the user out everywhere. Admin accounts cannot be changed.
		 */
		patch: {
			parameters: {
				query?: never
				header?: never
				path: {
					/** @description Unique identifier (UUID) */
					id: string
				}
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['UpdateUserRequest']
				}
			}
			responses: {
				/** @description User updated */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['User']
					}
				}
				/** @description Validation error */
				400: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Admin accounts cannot be changed */
				403: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		trace?: never
	}
	'/api/users/{id}/activity': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get a user's recent activity
		 * @description Newest first: sign-ins, changes to how they sign in, and what admins did.
		 */
		get: {
			parameters: {
				query?: never
				header?: never
				path: {
					/** @description Unique identifier (UUID) */
					id: string
				}
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Recent activity */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['ActivityList']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/security/threats': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * List detected threats
		 * @description Newest first, at most 100.
		 */
		get: {
			parameters: {
				query?: {
					/** @description Only resolved, or only open, threats */
					resolved?: 'true' | 'false'
				}
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Threats */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['ThreatList']
					}
				}
				/** @description Security monitoring is unavailable */
				503: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/security/threats/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		/** Resolve or reopen a threat */
		patch: {
			parameters: {
				query?: never
				header?: never
				path: {
					/** @description Unique identifier (UUID) */
					id: string
				}
				cookie?: never
			}
			requestBody: {
				content: {
					'application/json': components['schemas']['ResolveThreat']
				}
			}
			responses: {
				/** @description Threat updated */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Threat']
					}
				}
				/** @description Threat not found */
				404: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Security monitoring is unavailable */
				503: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		trace?: never
	}
	'/api/security/bans': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** List the bans in force */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Bans */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['BanList']
					}
				}
				/** @description Security monitoring is unavailable */
				503: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/security/bans/{ip}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		/** Lift a ban */
		delete: {
			parameters: {
				query?: never
				header?: never
				path: {
					/** @description IPv4 or IPv6 address */
					ip: string
				}
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Ban lifted */
				204: {
					headers: {
						[name: string]: unknown
					}
					content?: never
				}
				/** @description Address not banned */
				404: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
				/** @description Security monitoring is unavailable */
				503: {
					headers: {
						[name: string]: unknown
					}
					content: {
						'application/json': components['schemas']['Error']
					}
				}
			}
		}
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		Session: {
			/** @description SHA-256 of the session token, hex */
			id: string
			/**
			 * Format: date-time
			 * @description ISO 8601 datetime
			 * @example 2026-01-01T00:00:00.000Z
			 */
			created_at: string
			/**
			 * Format: date-time
			 * @description ISO 8601 datetime
			 * @example 2026-01-01T00:00:00.000Z
			 */
			expires_at: string
			/** @description Whether the session passed a second step: a passkey sign-in, or a passkey, app code or recovery code checked on it */
			two_step: boolean
			user: components['schemas']['User']
		}
		User: {
			/**
			 * Format: uuid
			 * @description Unique identifier (UUID)
			 * @example 550e8400-e29b-41d4-a716-446655440000
			 */
			id: string
			/**
			 * Format: email
			 * @example user@example.com
			 */
			email: string
			is_active: boolean
			is_verified: boolean
			/** @description The roles of the account; none means it can change nothing */
			roles: ('user' | 'admin')[]
			/**
			 * Format: date-time
			 * @description ISO 8601 datetime
			 * @example 2026-01-01T00:00:00.000Z
			 */
			created_at: string
			/**
			 * Format: date-time
			 * @description ISO 8601 datetime
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updated_at: string
		}
		Error: {
			error: string
			message: string
			statusCode: number
			/** @description A stable name for the error, when the service gives one */
			code?: string
		}
		LoginRequest: {
			/**
			 * Format: email
			 * @example user@example.com
			 */
			email: string
			/** @description Login password */
			password: string
		}
		/** @description WebAuthn options, as the browser API expects them */
		PasskeyOptions: unknown
		/** @description The credential the browser API returned */
		PasskeyCredential: unknown
		Message: {
			message: string
		}
		ActivityList: {
			data: components['schemas']['Activity'][]
			/** @description Total number of items */
			total: number
		}
		Activity: {
			/**
			 * Format: uuid
			 * @description Unique identifier (UUID)
			 * @example 550e8400-e29b-41d4-a716-446655440000
			 */
			id: string
			action: components['schemas']['ActivityAction']
			/**
			 * @description More about the action: how the user signed in, or which provider
			 * @example passkey
			 */
			detail: string | null
			/**
			 * Format: uuid
			 * @description Who did it: the user, an admin, or null for the operator
			 * @example 550e8400-e29b-41d4-a716-446655440000
			 */
			actor_id: string | null
			ip: string | null
			/**
			 * Format: date-time
			 * @description ISO 8601 datetime
			 * @example 2026-01-01T00:00:00.000Z
			 */
			created_at: string
		}
		/** @enum {string} */
		ActivityAction:
			| 'signed_in'
			| 'signed_out_elsewhere'
			| 'email_verified'
			| 'password_reset'
			| 'passkey_added'
			| 'passkey_removed'
			| 'authenticator_added'
			| 'authenticator_removed'
			| 'recovery_codes_created'
			| 'account_connected'
			| 'account_disconnected'
			| 'deactivated'
			| 'reactivated'
			| 'promoted'
			| 'demoted'
			| 'second_factors_reset'
		SecondFactorRequest:
			| {
					/** @description Code from the authenticator app */
					totp: string
			  }
			| {
					/** @description An unused recovery code */
					recovery_code: string
			  }
			| {
					passkey: components['schemas']['PasskeyCredential']
			  }
		RegisterOptions: {
			/** @description The key to show Turnstile with, or null when sign-up has no check */
			turnstile_site_key: string | null
		}
		RegisterRequest: {
			/**
			 * Format: email
			 * @example user@example.com
			 */
			email: string
			/** @description Password (8 to 128 characters) */
			password: string
			name?: string
			/** @description The token of the Turnstile widget, when sign-up has one */
			turnstile_token?: string
		}
		VerifyEmailRequest: {
			/** @description The token from the emailed link */
			token: string
		}
		ResetPasswordRequest: {
			/**
			 * Format: email
			 * @example user@example.com
			 */
			email: string
		}
		NewPasswordRequest: {
			/** @description The token from the emailed link */
			token: string
			/** @description Password (8 to 128 characters) */
			password: string
		}
		PasskeyList: {
			data: components['schemas']['Passkey'][]
			/** @description Total number of items */
			total: number
		}
		Passkey: {
			/** @description Credential ID, base64url */
			id: string
			/**
			 * Format: date-time
			 * @description ISO 8601 datetime
			 * @example 2026-01-01T00:00:00.000Z
			 */
			created_at: string
		}
		Factors: {
			/** @description Whether sign-in takes a second step */
			enabled: boolean
			passkeys: number
			/** @description Whether an authenticator app is on */
			totp: boolean
			/** @description Unused recovery codes */
			recovery_codes: number
		}
		TotpSetup: {
			/** @description The secret, base32, for typing into an app */
			secret: string
			/** @description The `otpauth://` URI, for a QR code */
			uri: string
		}
		TotpConfirm: {
			/** @description A code the app shows now */
			code: string
		}
		RecoveryCodes: {
			/** @description Shown this once */
			codes: string[]
		}
		OAuthProviders: {
			/** @description The providers set up */
			providers: ('github' | 'google')[]
		}
		Identities: {
			identities: components['schemas']['Identity'][]
		}
		Identity: {
			/** @enum {string} */
			provider: 'github' | 'google'
			/** @description The verified email of the account */
			email: string | null
			created_at: string
		}
		HealthResponse: {
			/**
			 * @description Service health status
			 * @enum {string}
			 */
			status: 'healthy' | 'degraded' | 'unhealthy'
			version: string
			uptime: number
			services?: {
				[key: string]: {
					/**
					 * @description Connection status
					 * @enum {string}
					 */
					status: 'up' | 'down' | 'unknown'
					latency?: number
				}
			}
		}
		UserList: {
			data: components['schemas']['User'][]
			/** @description Total number of items */
			total: number
		}
		UpdateUserRequest: {
			is_active: boolean
		}
		ThreatList: {
			data: components['schemas']['Threat'][]
			/** @description Total number of items */
			total: number
		}
		Threat: {
			/**
			 * Format: uuid
			 * @description Unique identifier (UUID)
			 * @example 550e8400-e29b-41d4-a716-446655440000
			 */
			id: string
			threat_type: string
			/**
			 * @description Rule / threat severity
			 * @enum {string}
			 */
			severity: 'low' | 'medium' | 'high'
			/**
			 * @description IPv4 or IPv6 address
			 * @example 192.168.1.100
			 */
			ip: string
			details: {
				[key: string]: unknown
			}
			action_taken: string | null
			resolved: boolean
			/**
			 * Format: date-time
			 * @description ISO 8601 datetime
			 * @example 2026-01-01T00:00:00.000Z
			 */
			created_at: string
		}
		ResolveThreat: {
			/** @description Whether the threat has been handled */
			resolved: boolean
		}
		BanList: {
			data: components['schemas']['Ban'][]
			/** @description Total number of items */
			total: number
		}
		Ban: {
			/**
			 * Format: uuid
			 * @description Unique identifier (UUID)
			 * @example 550e8400-e29b-41d4-a716-446655440000
			 */
			id: string
			/**
			 * @description IPv4 or IPv6 address
			 * @example 192.168.1.100
			 */
			ip: string
			reason: string
			rule_id: string | null
			/**
			 * @description Origin of the ban
			 * @enum {string}
			 */
			created_by: 'system' | 'manual' | 'vidar'
			/** Format: date-time */
			expires_at: string | null
			/**
			 * Format: date-time
			 * @description ISO 8601 datetime
			 * @example 2026-01-01T00:00:00.000Z
			 */
			created_at: string
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
