import { iro } from '../ryu/iro'
import { ji } from '../ryu/ji'
import { omote } from '../ryu/omote'
import { sen } from '../ryu/sen'

export const pdfViewer = {
	base: ['relative flex flex-col', 'overflow-hidden', omote.surface, sen.border],
	toolbar: [
		'flex flex-nowrap items-center justify-between',
		'overflow-x-auto',
		'gap-xs',
		'px-2 py-1.5',
		'border-b',
		sen.borderColor,
		'shrink-0',
	],
	toolbarSection: ['flex items-center shrink-0', 'gap-xs'],
	pageStatus: [ji.size.sm, iro.text.muted, 'tabular-nums select-none whitespace-nowrap'],
	body: ['flex flex-1 min-h-0'],
	sidebar: [
		'flex flex-col shrink-0 w-56 min-h-0',
		'overflow-hidden',
		'border-r',
		sen.borderColor,
		'transition-[margin] duration-150 ease-in-out',
	],
	sidebarClosed: '-ml-56',
	sidebarHeader: [
		'flex items-center',
		'gap-xs',
		'px-3 py-2',
		ji.size.md,
		iro.text.muted,
		'font-semibold',
		'shrink-0',
		'select-none',
	],
	thumbnails: ['flex flex-col basis-0 grow shrink min-h-0', 'gap-sm', 'overflow-y-auto px-4 pb-4'],
	thumbnailsGrid: ['grid grid-cols-2', 'gap-sm'],
	thumbnail: [
		'group/thumb',
		'flex flex-col items-center',
		'gap-sm',
		'bg-transparent',
		'outline-none',
		'cursor-pointer',
	],
	thumbnailFrame: [
		'relative block w-full aspect-[3/4]',
		'overflow-hidden',
		'opacity-50',
		'after:pointer-events-none after:absolute after:inset-0 after:ring-inset',
		'group-focus-visible/thumb:after:ring-4',
		'group-focus-visible/thumb:after:ring-blue-600',
		'group-focus-visible/thumb:opacity-75',
		'group-data-active/thumb:opacity-100',
		'group-hover/thumb:opacity-75',
		'group-data-active/thumb:hover:opacity-100',
	],
	thumbnailImage: ['block w-full h-full object-contain'],
	thumbnailFallback: ['flex items-center justify-center h-full w-full', ji.size.sm, iro.text.muted],
	thumbnailPlaceholder: ['block w-full aspect-[3/4]', omote.skeleton],
	thumbnailLabel: [
		ji.size.sm,
		iro.text.muted,
		'group-data-active/thumb:text-zinc-950 dark:group-data-active/thumb:text-white',
		'tabular-nums select-none',
	],
	viewport: [
		'overflow-auto',
		'flex items-safe-center justify-safe-center',
		'flex-1 min-w-0',
		'max-h-[min(1280px)]',
		'box-content p-4',
		'bg-zinc-100 dark:bg-zinc-900',
	],
	pageFrame: ['relative shrink-0'],
	page: ['absolute top-1/2 left-1/2 origin-center', 'shadow-lg', 'bg-white'],
	pagePlaceholder: ['w-full h-full', omote.skeleton],
	pageEmpty: ['flex items-center justify-center w-full h-full', 'py-2', ji.size.sm, iro.text.muted],
}
