import { mode } from '../../core/recipe'
import { hannou, iro, ji, narabi, omote, sen } from '../kiso'

export const k = {
	base: ['relative', narabi.col, 'overflow-hidden', omote.bg.surface, sen.border.default],
	toolbar: [
		'flex flex-nowrap items-center justify-between',
		'overflow-x-auto',
		'gap-1',
		'px-2 py-1.5',
		'border-b',
		sen.border.color,
		'shrink-0',
	],
	toolbarSection: [narabi.row, 'shrink-0', 'gap-1'],
	pageStatus: [ji.size.sm, iro.text.muted, 'tabular-nums select-none whitespace-nowrap'],
	body: ['flex flex-1 min-h-0'],
	sidebar: [
		narabi.col,
		'shrink-0 w-56 min-h-0',
		'overflow-hidden',
		'border-r',
		sen.border.color,
		'transition-[margin] duration-150 ease-in-out',
	],
	sidebarClosed: '-ml-56',
	sidebarHeader: [
		narabi.row,
		'gap-1',
		'px-3 py-2',
		ji.size.md,
		iro.text.muted,
		ji.weight.semibold,
		'shrink-0',
		'select-none',
	],
	thumbnails: [narabi.col, 'basis-0 grow shrink min-h-0', 'gap-2', 'overflow-y-auto px-4 pb-4'],
	thumbnailsGrid: ['grid grid-cols-2', 'gap-2'],
	thumbnail: [
		'group/thumb',
		narabi.col,
		'items-center',
		'gap-2',
		'bg-transparent',
		'outline-none',
		...hannou.cursor,
	],
	thumbnailFrame: [
		'relative block w-full aspect-[3/4]',
		'overflow-hidden',
		'opacity-50',
		'after:pointer-events-none after:absolute after:inset-0 after:ring-inset',
		'group-focus-visible/thumb:after:ring-4',
		'group-focus-visible/thumb:after:ring-blue-600',
		'group-focus-visible/thumb:opacity-75',
		'group-data-current/thumb:opacity-100',
		'group-hover/thumb:opacity-75',
		'group-data-current/thumb:hover:opacity-100',
	],
	thumbnailImage: ['block w-full h-full object-contain'],
	thumbnailFallback: [narabi.row, 'justify-center', 'h-full w-full', ji.size.sm, iro.text.muted],
	thumbnailPlaceholder: ['block w-full aspect-[3/4]', omote.skeleton],
	thumbnailLabel: [
		ji.size.sm,
		iro.text.muted,
		...mode('group-data-current/thumb:text-zinc-950', 'dark:group-data-current/thumb:text-white'),
		'tabular-nums select-none',
	],
	viewport: [
		'overflow-auto',
		'flex items-safe-center justify-safe-center',
		'flex-1 min-w-0',
		'max-h-[min(1280px)]',
		'box-content p-4',
		...mode('bg-zinc-100', 'dark:bg-zinc-900'),
	],
	pageFrame: ['relative shrink-0'],
	page: ['absolute top-1/2 left-1/2 origin-center', 'shadow-lg', 'bg-white'],
	pagePlaceholder: ['w-full h-full', omote.skeleton],
	pageEmpty: [narabi.row, 'justify-center', 'w-full h-full', 'py-2', ji.size.sm, iro.text.muted],
} as const
