export {
	Table,
	TableBody,
	type TableBodyProps,
	TableCell,
	type TableCellProps,
	TableHead,
	TableHeader,
	type TableHeaderProps,
	type TableHeadProps,
	type TableProps,
	TableRow,
	type TableRowProps,
	type TableVariants,
} from './component'
