/**
 * The packed CMaps, for a CJK font that a PDF encodes with a predefined CMap.
 *
 * @remarks Each file is a `new URL(…, import.meta.url)` of its own, as in
 * `pdf-viewer-binary-data.ts`. This module loads only when pdf.js asks for a CMap.
 * @internal
 */
export const CMAP_FILES: Record<string, URL> = {
	'78-EUC-H.bcmap': new URL('pdfjs-dist/cmaps/78-EUC-H.bcmap', import.meta.url),
	'78-EUC-V.bcmap': new URL('pdfjs-dist/cmaps/78-EUC-V.bcmap', import.meta.url),
	'78-H.bcmap': new URL('pdfjs-dist/cmaps/78-H.bcmap', import.meta.url),
	'78-RKSJ-H.bcmap': new URL('pdfjs-dist/cmaps/78-RKSJ-H.bcmap', import.meta.url),
	'78-RKSJ-V.bcmap': new URL('pdfjs-dist/cmaps/78-RKSJ-V.bcmap', import.meta.url),
	'78-V.bcmap': new URL('pdfjs-dist/cmaps/78-V.bcmap', import.meta.url),
	'78ms-RKSJ-H.bcmap': new URL('pdfjs-dist/cmaps/78ms-RKSJ-H.bcmap', import.meta.url),
	'78ms-RKSJ-V.bcmap': new URL('pdfjs-dist/cmaps/78ms-RKSJ-V.bcmap', import.meta.url),
	'83pv-RKSJ-H.bcmap': new URL('pdfjs-dist/cmaps/83pv-RKSJ-H.bcmap', import.meta.url),
	'90ms-RKSJ-H.bcmap': new URL('pdfjs-dist/cmaps/90ms-RKSJ-H.bcmap', import.meta.url),
	'90ms-RKSJ-V.bcmap': new URL('pdfjs-dist/cmaps/90ms-RKSJ-V.bcmap', import.meta.url),
	'90msp-RKSJ-H.bcmap': new URL('pdfjs-dist/cmaps/90msp-RKSJ-H.bcmap', import.meta.url),
	'90msp-RKSJ-V.bcmap': new URL('pdfjs-dist/cmaps/90msp-RKSJ-V.bcmap', import.meta.url),
	'90pv-RKSJ-H.bcmap': new URL('pdfjs-dist/cmaps/90pv-RKSJ-H.bcmap', import.meta.url),
	'90pv-RKSJ-V.bcmap': new URL('pdfjs-dist/cmaps/90pv-RKSJ-V.bcmap', import.meta.url),
	'Add-H.bcmap': new URL('pdfjs-dist/cmaps/Add-H.bcmap', import.meta.url),
	'Add-RKSJ-H.bcmap': new URL('pdfjs-dist/cmaps/Add-RKSJ-H.bcmap', import.meta.url),
	'Add-RKSJ-V.bcmap': new URL('pdfjs-dist/cmaps/Add-RKSJ-V.bcmap', import.meta.url),
	'Add-V.bcmap': new URL('pdfjs-dist/cmaps/Add-V.bcmap', import.meta.url),
	'Adobe-CNS1-0.bcmap': new URL('pdfjs-dist/cmaps/Adobe-CNS1-0.bcmap', import.meta.url),
	'Adobe-CNS1-1.bcmap': new URL('pdfjs-dist/cmaps/Adobe-CNS1-1.bcmap', import.meta.url),
	'Adobe-CNS1-2.bcmap': new URL('pdfjs-dist/cmaps/Adobe-CNS1-2.bcmap', import.meta.url),
	'Adobe-CNS1-3.bcmap': new URL('pdfjs-dist/cmaps/Adobe-CNS1-3.bcmap', import.meta.url),
	'Adobe-CNS1-4.bcmap': new URL('pdfjs-dist/cmaps/Adobe-CNS1-4.bcmap', import.meta.url),
	'Adobe-CNS1-5.bcmap': new URL('pdfjs-dist/cmaps/Adobe-CNS1-5.bcmap', import.meta.url),
	'Adobe-CNS1-6.bcmap': new URL('pdfjs-dist/cmaps/Adobe-CNS1-6.bcmap', import.meta.url),
	'Adobe-CNS1-UCS2.bcmap': new URL('pdfjs-dist/cmaps/Adobe-CNS1-UCS2.bcmap', import.meta.url),
	'Adobe-GB1-0.bcmap': new URL('pdfjs-dist/cmaps/Adobe-GB1-0.bcmap', import.meta.url),
	'Adobe-GB1-1.bcmap': new URL('pdfjs-dist/cmaps/Adobe-GB1-1.bcmap', import.meta.url),
	'Adobe-GB1-2.bcmap': new URL('pdfjs-dist/cmaps/Adobe-GB1-2.bcmap', import.meta.url),
	'Adobe-GB1-3.bcmap': new URL('pdfjs-dist/cmaps/Adobe-GB1-3.bcmap', import.meta.url),
	'Adobe-GB1-4.bcmap': new URL('pdfjs-dist/cmaps/Adobe-GB1-4.bcmap', import.meta.url),
	'Adobe-GB1-5.bcmap': new URL('pdfjs-dist/cmaps/Adobe-GB1-5.bcmap', import.meta.url),
	'Adobe-GB1-UCS2.bcmap': new URL('pdfjs-dist/cmaps/Adobe-GB1-UCS2.bcmap', import.meta.url),
	'Adobe-Japan1-0.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Japan1-0.bcmap', import.meta.url),
	'Adobe-Japan1-1.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Japan1-1.bcmap', import.meta.url),
	'Adobe-Japan1-2.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Japan1-2.bcmap', import.meta.url),
	'Adobe-Japan1-3.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Japan1-3.bcmap', import.meta.url),
	'Adobe-Japan1-4.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Japan1-4.bcmap', import.meta.url),
	'Adobe-Japan1-5.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Japan1-5.bcmap', import.meta.url),
	'Adobe-Japan1-6.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Japan1-6.bcmap', import.meta.url),
	'Adobe-Japan1-UCS2.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Japan1-UCS2.bcmap', import.meta.url),
	'Adobe-Korea1-0.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Korea1-0.bcmap', import.meta.url),
	'Adobe-Korea1-1.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Korea1-1.bcmap', import.meta.url),
	'Adobe-Korea1-2.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Korea1-2.bcmap', import.meta.url),
	'Adobe-Korea1-UCS2.bcmap': new URL('pdfjs-dist/cmaps/Adobe-Korea1-UCS2.bcmap', import.meta.url),
	'B5-H.bcmap': new URL('pdfjs-dist/cmaps/B5-H.bcmap', import.meta.url),
	'B5-V.bcmap': new URL('pdfjs-dist/cmaps/B5-V.bcmap', import.meta.url),
	'B5pc-H.bcmap': new URL('pdfjs-dist/cmaps/B5pc-H.bcmap', import.meta.url),
	'B5pc-V.bcmap': new URL('pdfjs-dist/cmaps/B5pc-V.bcmap', import.meta.url),
	'CNS-EUC-H.bcmap': new URL('pdfjs-dist/cmaps/CNS-EUC-H.bcmap', import.meta.url),
	'CNS-EUC-V.bcmap': new URL('pdfjs-dist/cmaps/CNS-EUC-V.bcmap', import.meta.url),
	'CNS1-H.bcmap': new URL('pdfjs-dist/cmaps/CNS1-H.bcmap', import.meta.url),
	'CNS1-V.bcmap': new URL('pdfjs-dist/cmaps/CNS1-V.bcmap', import.meta.url),
	'CNS2-H.bcmap': new URL('pdfjs-dist/cmaps/CNS2-H.bcmap', import.meta.url),
	'CNS2-V.bcmap': new URL('pdfjs-dist/cmaps/CNS2-V.bcmap', import.meta.url),
	'ETHK-B5-H.bcmap': new URL('pdfjs-dist/cmaps/ETHK-B5-H.bcmap', import.meta.url),
	'ETHK-B5-V.bcmap': new URL('pdfjs-dist/cmaps/ETHK-B5-V.bcmap', import.meta.url),
	'ETen-B5-H.bcmap': new URL('pdfjs-dist/cmaps/ETen-B5-H.bcmap', import.meta.url),
	'ETen-B5-V.bcmap': new URL('pdfjs-dist/cmaps/ETen-B5-V.bcmap', import.meta.url),
	'ETenms-B5-H.bcmap': new URL('pdfjs-dist/cmaps/ETenms-B5-H.bcmap', import.meta.url),
	'ETenms-B5-V.bcmap': new URL('pdfjs-dist/cmaps/ETenms-B5-V.bcmap', import.meta.url),
	'EUC-H.bcmap': new URL('pdfjs-dist/cmaps/EUC-H.bcmap', import.meta.url),
	'EUC-V.bcmap': new URL('pdfjs-dist/cmaps/EUC-V.bcmap', import.meta.url),
	'Ext-H.bcmap': new URL('pdfjs-dist/cmaps/Ext-H.bcmap', import.meta.url),
	'Ext-RKSJ-H.bcmap': new URL('pdfjs-dist/cmaps/Ext-RKSJ-H.bcmap', import.meta.url),
	'Ext-RKSJ-V.bcmap': new URL('pdfjs-dist/cmaps/Ext-RKSJ-V.bcmap', import.meta.url),
	'Ext-V.bcmap': new URL('pdfjs-dist/cmaps/Ext-V.bcmap', import.meta.url),
	'GB-EUC-H.bcmap': new URL('pdfjs-dist/cmaps/GB-EUC-H.bcmap', import.meta.url),
	'GB-EUC-V.bcmap': new URL('pdfjs-dist/cmaps/GB-EUC-V.bcmap', import.meta.url),
	'GB-H.bcmap': new URL('pdfjs-dist/cmaps/GB-H.bcmap', import.meta.url),
	'GB-V.bcmap': new URL('pdfjs-dist/cmaps/GB-V.bcmap', import.meta.url),
	'GBK-EUC-H.bcmap': new URL('pdfjs-dist/cmaps/GBK-EUC-H.bcmap', import.meta.url),
	'GBK-EUC-V.bcmap': new URL('pdfjs-dist/cmaps/GBK-EUC-V.bcmap', import.meta.url),
	'GBK2K-H.bcmap': new URL('pdfjs-dist/cmaps/GBK2K-H.bcmap', import.meta.url),
	'GBK2K-V.bcmap': new URL('pdfjs-dist/cmaps/GBK2K-V.bcmap', import.meta.url),
	'GBKp-EUC-H.bcmap': new URL('pdfjs-dist/cmaps/GBKp-EUC-H.bcmap', import.meta.url),
	'GBKp-EUC-V.bcmap': new URL('pdfjs-dist/cmaps/GBKp-EUC-V.bcmap', import.meta.url),
	'GBT-EUC-H.bcmap': new URL('pdfjs-dist/cmaps/GBT-EUC-H.bcmap', import.meta.url),
	'GBT-EUC-V.bcmap': new URL('pdfjs-dist/cmaps/GBT-EUC-V.bcmap', import.meta.url),
	'GBT-H.bcmap': new URL('pdfjs-dist/cmaps/GBT-H.bcmap', import.meta.url),
	'GBT-V.bcmap': new URL('pdfjs-dist/cmaps/GBT-V.bcmap', import.meta.url),
	'GBTpc-EUC-H.bcmap': new URL('pdfjs-dist/cmaps/GBTpc-EUC-H.bcmap', import.meta.url),
	'GBTpc-EUC-V.bcmap': new URL('pdfjs-dist/cmaps/GBTpc-EUC-V.bcmap', import.meta.url),
	'GBpc-EUC-H.bcmap': new URL('pdfjs-dist/cmaps/GBpc-EUC-H.bcmap', import.meta.url),
	'GBpc-EUC-V.bcmap': new URL('pdfjs-dist/cmaps/GBpc-EUC-V.bcmap', import.meta.url),
	'H.bcmap': new URL('pdfjs-dist/cmaps/H.bcmap', import.meta.url),
	'HKdla-B5-H.bcmap': new URL('pdfjs-dist/cmaps/HKdla-B5-H.bcmap', import.meta.url),
	'HKdla-B5-V.bcmap': new URL('pdfjs-dist/cmaps/HKdla-B5-V.bcmap', import.meta.url),
	'HKdlb-B5-H.bcmap': new URL('pdfjs-dist/cmaps/HKdlb-B5-H.bcmap', import.meta.url),
	'HKdlb-B5-V.bcmap': new URL('pdfjs-dist/cmaps/HKdlb-B5-V.bcmap', import.meta.url),
	'HKgccs-B5-H.bcmap': new URL('pdfjs-dist/cmaps/HKgccs-B5-H.bcmap', import.meta.url),
	'HKgccs-B5-V.bcmap': new URL('pdfjs-dist/cmaps/HKgccs-B5-V.bcmap', import.meta.url),
	'HKm314-B5-H.bcmap': new URL('pdfjs-dist/cmaps/HKm314-B5-H.bcmap', import.meta.url),
	'HKm314-B5-V.bcmap': new URL('pdfjs-dist/cmaps/HKm314-B5-V.bcmap', import.meta.url),
	'HKm471-B5-H.bcmap': new URL('pdfjs-dist/cmaps/HKm471-B5-H.bcmap', import.meta.url),
	'HKm471-B5-V.bcmap': new URL('pdfjs-dist/cmaps/HKm471-B5-V.bcmap', import.meta.url),
	'HKscs-B5-H.bcmap': new URL('pdfjs-dist/cmaps/HKscs-B5-H.bcmap', import.meta.url),
	'HKscs-B5-V.bcmap': new URL('pdfjs-dist/cmaps/HKscs-B5-V.bcmap', import.meta.url),
	'Hankaku.bcmap': new URL('pdfjs-dist/cmaps/Hankaku.bcmap', import.meta.url),
	'Hiragana.bcmap': new URL('pdfjs-dist/cmaps/Hiragana.bcmap', import.meta.url),
	'KSC-EUC-H.bcmap': new URL('pdfjs-dist/cmaps/KSC-EUC-H.bcmap', import.meta.url),
	'KSC-EUC-V.bcmap': new URL('pdfjs-dist/cmaps/KSC-EUC-V.bcmap', import.meta.url),
	'KSC-H.bcmap': new URL('pdfjs-dist/cmaps/KSC-H.bcmap', import.meta.url),
	'KSC-Johab-H.bcmap': new URL('pdfjs-dist/cmaps/KSC-Johab-H.bcmap', import.meta.url),
	'KSC-Johab-V.bcmap': new URL('pdfjs-dist/cmaps/KSC-Johab-V.bcmap', import.meta.url),
	'KSC-V.bcmap': new URL('pdfjs-dist/cmaps/KSC-V.bcmap', import.meta.url),
	'KSCms-UHC-H.bcmap': new URL('pdfjs-dist/cmaps/KSCms-UHC-H.bcmap', import.meta.url),
	'KSCms-UHC-HW-H.bcmap': new URL('pdfjs-dist/cmaps/KSCms-UHC-HW-H.bcmap', import.meta.url),
	'KSCms-UHC-HW-V.bcmap': new URL('pdfjs-dist/cmaps/KSCms-UHC-HW-V.bcmap', import.meta.url),
	'KSCms-UHC-V.bcmap': new URL('pdfjs-dist/cmaps/KSCms-UHC-V.bcmap', import.meta.url),
	'KSCpc-EUC-H.bcmap': new URL('pdfjs-dist/cmaps/KSCpc-EUC-H.bcmap', import.meta.url),
	'KSCpc-EUC-V.bcmap': new URL('pdfjs-dist/cmaps/KSCpc-EUC-V.bcmap', import.meta.url),
	'Katakana.bcmap': new URL('pdfjs-dist/cmaps/Katakana.bcmap', import.meta.url),
	'NWP-H.bcmap': new URL('pdfjs-dist/cmaps/NWP-H.bcmap', import.meta.url),
	'NWP-V.bcmap': new URL('pdfjs-dist/cmaps/NWP-V.bcmap', import.meta.url),
	'RKSJ-H.bcmap': new URL('pdfjs-dist/cmaps/RKSJ-H.bcmap', import.meta.url),
	'RKSJ-V.bcmap': new URL('pdfjs-dist/cmaps/RKSJ-V.bcmap', import.meta.url),
	'Roman.bcmap': new URL('pdfjs-dist/cmaps/Roman.bcmap', import.meta.url),
	'UniCNS-UCS2-H.bcmap': new URL('pdfjs-dist/cmaps/UniCNS-UCS2-H.bcmap', import.meta.url),
	'UniCNS-UCS2-V.bcmap': new URL('pdfjs-dist/cmaps/UniCNS-UCS2-V.bcmap', import.meta.url),
	'UniCNS-UTF16-H.bcmap': new URL('pdfjs-dist/cmaps/UniCNS-UTF16-H.bcmap', import.meta.url),
	'UniCNS-UTF16-V.bcmap': new URL('pdfjs-dist/cmaps/UniCNS-UTF16-V.bcmap', import.meta.url),
	'UniCNS-UTF32-H.bcmap': new URL('pdfjs-dist/cmaps/UniCNS-UTF32-H.bcmap', import.meta.url),
	'UniCNS-UTF32-V.bcmap': new URL('pdfjs-dist/cmaps/UniCNS-UTF32-V.bcmap', import.meta.url),
	'UniCNS-UTF8-H.bcmap': new URL('pdfjs-dist/cmaps/UniCNS-UTF8-H.bcmap', import.meta.url),
	'UniCNS-UTF8-V.bcmap': new URL('pdfjs-dist/cmaps/UniCNS-UTF8-V.bcmap', import.meta.url),
	'UniGB-UCS2-H.bcmap': new URL('pdfjs-dist/cmaps/UniGB-UCS2-H.bcmap', import.meta.url),
	'UniGB-UCS2-V.bcmap': new URL('pdfjs-dist/cmaps/UniGB-UCS2-V.bcmap', import.meta.url),
	'UniGB-UTF16-H.bcmap': new URL('pdfjs-dist/cmaps/UniGB-UTF16-H.bcmap', import.meta.url),
	'UniGB-UTF16-V.bcmap': new URL('pdfjs-dist/cmaps/UniGB-UTF16-V.bcmap', import.meta.url),
	'UniGB-UTF32-H.bcmap': new URL('pdfjs-dist/cmaps/UniGB-UTF32-H.bcmap', import.meta.url),
	'UniGB-UTF32-V.bcmap': new URL('pdfjs-dist/cmaps/UniGB-UTF32-V.bcmap', import.meta.url),
	'UniGB-UTF8-H.bcmap': new URL('pdfjs-dist/cmaps/UniGB-UTF8-H.bcmap', import.meta.url),
	'UniGB-UTF8-V.bcmap': new URL('pdfjs-dist/cmaps/UniGB-UTF8-V.bcmap', import.meta.url),
	'UniJIS-UCS2-H.bcmap': new URL('pdfjs-dist/cmaps/UniJIS-UCS2-H.bcmap', import.meta.url),
	'UniJIS-UCS2-HW-H.bcmap': new URL('pdfjs-dist/cmaps/UniJIS-UCS2-HW-H.bcmap', import.meta.url),
	'UniJIS-UCS2-HW-V.bcmap': new URL('pdfjs-dist/cmaps/UniJIS-UCS2-HW-V.bcmap', import.meta.url),
	'UniJIS-UCS2-V.bcmap': new URL('pdfjs-dist/cmaps/UniJIS-UCS2-V.bcmap', import.meta.url),
	'UniJIS-UTF16-H.bcmap': new URL('pdfjs-dist/cmaps/UniJIS-UTF16-H.bcmap', import.meta.url),
	'UniJIS-UTF16-V.bcmap': new URL('pdfjs-dist/cmaps/UniJIS-UTF16-V.bcmap', import.meta.url),
	'UniJIS-UTF32-H.bcmap': new URL('pdfjs-dist/cmaps/UniJIS-UTF32-H.bcmap', import.meta.url),
	'UniJIS-UTF32-V.bcmap': new URL('pdfjs-dist/cmaps/UniJIS-UTF32-V.bcmap', import.meta.url),
	'UniJIS-UTF8-H.bcmap': new URL('pdfjs-dist/cmaps/UniJIS-UTF8-H.bcmap', import.meta.url),
	'UniJIS-UTF8-V.bcmap': new URL('pdfjs-dist/cmaps/UniJIS-UTF8-V.bcmap', import.meta.url),
	'UniJIS2004-UTF16-H.bcmap': new URL('pdfjs-dist/cmaps/UniJIS2004-UTF16-H.bcmap', import.meta.url),
	'UniJIS2004-UTF16-V.bcmap': new URL('pdfjs-dist/cmaps/UniJIS2004-UTF16-V.bcmap', import.meta.url),
	'UniJIS2004-UTF32-H.bcmap': new URL('pdfjs-dist/cmaps/UniJIS2004-UTF32-H.bcmap', import.meta.url),
	'UniJIS2004-UTF32-V.bcmap': new URL('pdfjs-dist/cmaps/UniJIS2004-UTF32-V.bcmap', import.meta.url),
	'UniJIS2004-UTF8-H.bcmap': new URL('pdfjs-dist/cmaps/UniJIS2004-UTF8-H.bcmap', import.meta.url),
	'UniJIS2004-UTF8-V.bcmap': new URL('pdfjs-dist/cmaps/UniJIS2004-UTF8-V.bcmap', import.meta.url),
	'UniJISPro-UCS2-HW-V.bcmap': new URL(
		'pdfjs-dist/cmaps/UniJISPro-UCS2-HW-V.bcmap',
		import.meta.url,
	),
	'UniJISPro-UCS2-V.bcmap': new URL('pdfjs-dist/cmaps/UniJISPro-UCS2-V.bcmap', import.meta.url),
	'UniJISPro-UTF8-V.bcmap': new URL('pdfjs-dist/cmaps/UniJISPro-UTF8-V.bcmap', import.meta.url),
	'UniJISX0213-UTF32-H.bcmap': new URL(
		'pdfjs-dist/cmaps/UniJISX0213-UTF32-H.bcmap',
		import.meta.url,
	),
	'UniJISX0213-UTF32-V.bcmap': new URL(
		'pdfjs-dist/cmaps/UniJISX0213-UTF32-V.bcmap',
		import.meta.url,
	),
	'UniJISX02132004-UTF32-H.bcmap': new URL(
		'pdfjs-dist/cmaps/UniJISX02132004-UTF32-H.bcmap',
		import.meta.url,
	),
	'UniJISX02132004-UTF32-V.bcmap': new URL(
		'pdfjs-dist/cmaps/UniJISX02132004-UTF32-V.bcmap',
		import.meta.url,
	),
	'UniKS-UCS2-H.bcmap': new URL('pdfjs-dist/cmaps/UniKS-UCS2-H.bcmap', import.meta.url),
	'UniKS-UCS2-V.bcmap': new URL('pdfjs-dist/cmaps/UniKS-UCS2-V.bcmap', import.meta.url),
	'UniKS-UTF16-H.bcmap': new URL('pdfjs-dist/cmaps/UniKS-UTF16-H.bcmap', import.meta.url),
	'UniKS-UTF16-V.bcmap': new URL('pdfjs-dist/cmaps/UniKS-UTF16-V.bcmap', import.meta.url),
	'UniKS-UTF32-H.bcmap': new URL('pdfjs-dist/cmaps/UniKS-UTF32-H.bcmap', import.meta.url),
	'UniKS-UTF32-V.bcmap': new URL('pdfjs-dist/cmaps/UniKS-UTF32-V.bcmap', import.meta.url),
	'UniKS-UTF8-H.bcmap': new URL('pdfjs-dist/cmaps/UniKS-UTF8-H.bcmap', import.meta.url),
	'UniKS-UTF8-V.bcmap': new URL('pdfjs-dist/cmaps/UniKS-UTF8-V.bcmap', import.meta.url),
	'V.bcmap': new URL('pdfjs-dist/cmaps/V.bcmap', import.meta.url),
	'WP-Symbol.bcmap': new URL('pdfjs-dist/cmaps/WP-Symbol.bcmap', import.meta.url),
}
