/** Kata (型) — Design token recipes. Each recipe captures one design concern as reusable Tailwind class fragments. */

export { garasu } from './garasu'
export { iro } from './iro'
export { ji } from './ji'
export { kage } from './kage'
export { katachi } from './katachi'
export { ki } from './ki'
export { kokkaku } from './kokkaku'
export { kumi } from './kumi'
export { kyousei } from './kyousei'
export { ma } from './ma'
export { maru } from './maru'
export { nagare } from './nagare'
export { narabi } from './narabi'
export { omote } from './omote'
export { sawari } from './sawari'
export { sen } from './sen'
export { take } from './take'
export { ugoki } from './ugoki'
export { waku } from './waku'
export { yasumi } from './yasumi'
