import { defineConfig } from 'tsup'

export default defineConfig({
	entry: {
		index: 'src/index.ts',
		alert: 'src/alert/index.ts',
		'auth-layout': 'src/auth-layout.tsx',
		avatar: 'src/avatar/index.ts',
		badge: 'src/badge/index.ts',
		button: 'src/button/index.ts',
		checkbox: 'src/checkbox/index.ts',
		combobox: 'src/combobox/index.ts',
		'description-list': 'src/description-list/index.ts',
		dialog: 'src/dialog/index.ts',
		divider: 'src/divider/index.ts',
		dropdown: 'src/dropdown/index.ts',
		fieldset: 'src/fieldset/index.ts',
		heading: 'src/heading/index.ts',
		input: 'src/input/index.ts',
		link: 'src/link.tsx',
		listbox: 'src/listbox/index.ts',
		navbar: 'src/navbar/index.ts',
		pagination: 'src/pagination/index.ts',
		radio: 'src/radio/index.ts',
		select: 'src/select/index.ts',
		sidebar: 'src/sidebar/index.ts',
		'sidebar-layout': 'src/sidebar-layout/index.ts',
		'stacked-layout': 'src/stacked-layout/index.ts',
		switch: 'src/switch/index.ts',
		table: 'src/table/index.ts',
		text: 'src/text/index.ts',
		textarea: 'src/textarea/index.ts',
		hooks: 'src/hooks/index.ts',
		utils: 'src/utils/index.ts',
	},
	format: ['esm'],
	target: 'node22',
	outDir: 'dist',
	clean: true,
	dts: true,
	sourcemap: true,
	splitting: false,
})
