import { defineConfig } from 'tsup'

export default defineConfig({
	entry: {
		index: 'src/index.ts',
		alert: 'src/alert.tsx',
		'auth-layout': 'src/auth-layout.tsx',
		avatar: 'src/avatar.tsx',
		badge: 'src/badge.tsx',
		button: 'src/button.tsx',
		checkbox: 'src/checkbox.tsx',
		combobox: 'src/combobox.tsx',
		'description-list': 'src/description-list.tsx',
		dialog: 'src/dialog.tsx',
		divider: 'src/divider.tsx',
		dropdown: 'src/dropdown.tsx',
		fieldset: 'src/fieldset.tsx',
		heading: 'src/heading.tsx',
		input: 'src/input.tsx',
		link: 'src/link.tsx',
		listbox: 'src/listbox.tsx',
		navbar: 'src/navbar.tsx',
		pagination: 'src/pagination.tsx',
		radio: 'src/radio.tsx',
		select: 'src/select.tsx',
		sidebar: 'src/sidebar.tsx',
		'sidebar-layout': 'src/sidebar-layout.tsx',
		'stacked-layout': 'src/stacked-layout.tsx',
		switch: 'src/switch.tsx',
		table: 'src/table.tsx',
		text: 'src/text.tsx',
		textarea: 'src/textarea.tsx',
	},
	format: ['esm'],
	target: 'node22',
	outDir: 'dist',
	clean: true,
	dts: true,
	sourcemap: true,
	splitting: false,
	jsx: 'automatic',
	jsxImportSource: 'react',
})
