import { describe, expect, it } from 'vitest'
import { defaultRegistry } from '../../../docs/derive-code/registry'

describe('defaultRegistry.byType', () => {
	it('reads __name / __module off a tagged function', () => {
		const Component = Object.assign(() => null, { __name: 'Button', __module: 'button' })

		expect(defaultRegistry.byType.get(Component)).toEqual({ name: 'Button', module: 'button' })
	})

	it('returns undefined for an untagged function', () => {
		const Plain = (() => null) as unknown

		expect(defaultRegistry.byType.get(Plain)).toBeUndefined()
	})

	it('returns undefined when only one of the two tags is present', () => {
		const Partial = Object.assign(() => null, { __name: 'Button' })

		expect(defaultRegistry.byType.get(Partial)).toBeUndefined()
	})

	it('returns undefined for null / undefined', () => {
		expect(defaultRegistry.byType.get(null)).toBeUndefined()

		expect(defaultRegistry.byType.get(undefined)).toBeUndefined()
	})

	it('returns undefined when tags are present but not strings', () => {
		const Bad = Object.assign(() => null, { __name: 42, __module: {} })

		expect(defaultRegistry.byType.get(Bad)).toBeUndefined()
	})
})

describe('defaultRegistry.byName', () => {
	// The byName map is populated from the `virtual:component-modules` map at
	// build/test time. The virtual module is generated by the componentTagsPlugin
	// over the real components dir.
	it('is a Map keyed by component name', () => {
		expect(defaultRegistry.byName).toBeInstanceOf(Map)
	})

	it('resolves a known component name back to its module', () => {
		// `Button` is the canonical recognizable export — it lives in components/button.
		const info = defaultRegistry.byName.get('Button')

		expect(info?.name).toBe('Button')

		expect(info?.module).toBe('button')
	})
})
