import type { DensityStep } from '../../core/density'

// The `size` axes of the documented components: each component whose `size`
// prop takes density steps, with the steps that the prop offers.
// `src/docs/__tests__/size-axes.test.ts` holds this list equal to the API data
// of the docs plugin, so a new axis or a changed axis must come here. The
// distinct-steps gate (`browser/geometry/size-steps.test.tsx`) renders each
// step of each axis.

/** The steps that the `size` prop of each documented component offers. */
export const SIZE_AXES = {
	AddressInput: ['xs', 'sm', 'md', 'lg', 'xl'],
	Avatar: ['xs', 'sm', 'md', 'lg', 'xl'],
	AvatarGroup: ['xs', 'sm', 'md', 'lg', 'xl'],
	AvatarSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Badge: ['xs', 'sm', 'md', 'lg', 'xl'],
	BadgeSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Button: ['xs', 'sm', 'md', 'lg', 'xl'],
	ButtonSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Calendar: ['xs', 'sm', 'md', 'lg', 'xl'],
	CalendarRange: ['xs', 'sm', 'md', 'lg', 'xl'],
	CalendarSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Card: ['xs', 'sm', 'md', 'lg', 'xl'],
	CardTitle: ['xs', 'sm', 'md', 'lg', 'xl'],
	ChartSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Checkbox: ['xs', 'sm', 'md', 'lg', 'xl'],
	CheckboxSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Code: ['xs', 'sm', 'md', 'lg', 'xl'],
	CodeBlock: ['xs', 'sm', 'md', 'lg', 'xl'],
	ColorPanel: ['xs', 'sm', 'md', 'lg', 'xl'],
	ColorPanelSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	ColorPicker: ['xs', 'sm', 'md', 'lg', 'xl'],
	ColorPickerSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Combobox: ['xs', 'sm', 'md', 'lg', 'xl'],
	CommandPaletteClose: ['xs', 'sm', 'md', 'lg', 'xl'],
	CommandPaletteShortcut: ['xs', 'sm', 'md', 'lg', 'xl'],
	Control: ['xs', 'sm', 'md', 'lg', 'xl'],
	ControlSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	CopyButton: ['xs', 'sm', 'md', 'lg', 'xl'],
	CreditCardInput: ['xs', 'sm', 'md', 'lg', 'xl'],
	CreditCardInputCvv: ['xs', 'sm', 'md', 'lg', 'xl'],
	CreditCardInputExpiry: ['xs', 'sm', 'md', 'lg', 'xl'],
	CurrencyInput: ['xs', 'sm', 'md', 'lg', 'xl'],
	DateInput: ['xs', 'sm', 'md', 'lg', 'xl'],
	DatePicker: ['xs', 'sm', 'md', 'lg', 'xl'],
	DatePickerSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	DrawerPanel: ['xs', 'sm', 'md', 'lg', 'xl'],
	FileUploadButton: ['xs', 'sm', 'md', 'lg', 'xl'],
	FileUploadInput: ['xs', 'sm', 'md', 'lg', 'xl'],
	Grid: ['xs', 'sm', 'md', 'lg', 'xl'],
	Group: ['xs', 'sm', 'md', 'lg', 'xl'],
	Heading: ['xs', 'sm', 'md', 'lg', 'xl'],
	HeadingSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	HoldButton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Icon: ['xs', 'sm', 'md', 'lg', 'xl'],
	Input: ['xs', 'sm', 'md', 'lg', 'xl'],
	Kbd: ['xs', 'sm', 'md', 'lg', 'xl'],
	Listbox: ['xs', 'sm', 'md', 'lg', 'xl'],
	LoadingDots: ['xs', 'sm', 'md', 'lg', 'xl'],
	LoadingSpinner: ['xs', 'sm', 'md', 'lg', 'xl'],
	MaskInput: ['xs', 'sm', 'md', 'lg', 'xl'],
	Menu: ['xs', 'sm', 'md', 'lg', 'xl'],
	MenuShortcut: ['xs', 'sm', 'md', 'lg', 'xl'],
	NumberInput: ['xs', 'sm', 'md', 'lg', 'xl'],
	PaginationNext: ['xs', 'sm', 'md', 'lg', 'xl'],
	PaginationPrevious: ['xs', 'sm', 'md', 'lg', 'xl'],
	PasswordConfirmNew: ['xs', 'sm', 'md', 'lg', 'xl'],
	PasswordConfirmRepeat: ['xs', 'sm', 'md', 'lg', 'xl'],
	PasswordInput: ['xs', 'sm', 'md', 'lg', 'xl'],
	PivotTable: ['xs', 'sm', 'md', 'lg', 'xl'],
	PopoverContent: ['sm', 'md', 'lg'],
	ProgressBar: ['xs', 'sm', 'md', 'lg', 'xl'],
	ProgressBarSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	ProgressGauge: ['xs', 'sm', 'md', 'lg', 'xl'],
	ProgressGaugeSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Radio: ['xs', 'sm', 'md', 'lg', 'xl'],
	RadioSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	RangeSlider: ['xs', 'sm', 'md', 'lg', 'xl'],
	Rating: ['xs', 'sm', 'md', 'lg', 'xl'],
	RatingSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	SearchInput: ['xs', 'sm', 'md', 'lg', 'xl'],
	Segment: ['xs', 'sm', 'md', 'lg', 'xl'],
	SegmentSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Select: ['xs', 'sm', 'md', 'lg', 'xl'],
	SidebarItem: ['xs', 'sm', 'md', 'lg', 'xl'],
	SidebarSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Slider: ['xs', 'sm', 'md', 'lg', 'xl'],
	SliderSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Sparkline: ['xs', 'sm', 'md', 'lg', 'xl'],
	SparklineSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	StatSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	StatValue: ['xs', 'sm', 'md', 'lg', 'xl'],
	StatValueSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	StatusDot: ['xs', 'sm', 'md', 'lg', 'xl'],
	Swatch: ['xs', 'sm', 'md', 'lg', 'xl'],
	Switch: ['xs', 'sm', 'md', 'lg', 'xl'],
	SwitchSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	TabListSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Table: ['xs', 'sm', 'md', 'lg', 'xl'],
	Tabs: ['xs', 'sm', 'md', 'lg', 'xl'],
	TagInput: ['xs', 'sm', 'md', 'lg', 'xl'],
	Text: ['xs', 'sm', 'md', 'lg', 'xl'],
	TextSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	Textarea: ['xs', 'sm', 'md', 'lg', 'xl'],
	TextareaSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	ToggleIconButton: ['xs', 'sm', 'md', 'lg', 'xl'],
	ToggleIconButtonSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
	TooltipContent: ['xs', 'sm', 'md', 'lg', 'xl'],
	Tree: ['xs', 'sm', 'md', 'lg', 'xl'],
	TreeSkeleton: ['xs', 'sm', 'md', 'lg', 'xl'],
} as const satisfies Record<string, readonly DensityStep[]>

/** The name of a component with a `size` axis. */
export type SizedComponent = keyof typeof SIZE_AXES
