import type { DensityStep } from '../../core/density'

// The `size` axes of the documented components: each component whose `size`
// prop takes density steps, with the steps that the prop offers.
// `docs/size-axes.test.ts` holds this list equal to the API that the docs site
// builds, so a new axis or a changed axis must come here. The distinct-steps
// gate (`browser/geometry/size-steps.test.tsx`) renders each step of each axis.

/** The steps that the `size` prop of each documented component offers. */
export const SIZE_AXES = {
	AddressInput: ['xs', 'sm', 'md', 'lg'],
	Avatar: ['sm', 'md', 'lg'],
	AvatarGroup: ['sm', 'md', 'lg'],
	AvatarSkeleton: ['sm', 'md', 'lg'],
	Badge: ['xs', 'sm', 'md', 'lg'],
	BadgeSkeleton: ['xs', 'sm', 'md', 'lg'],
	Button: ['xs', 'sm', 'md', 'lg'],
	ButtonSkeleton: ['xs', 'sm', 'md', 'lg'],
	Calendar: ['sm', 'md', 'lg'],
	CalendarRange: ['sm', 'md', 'lg'],
	CalendarSkeleton: ['sm', 'md', 'lg'],
	Card: ['sm', 'md', 'lg'],
	CardTitle: ['sm', 'md', 'lg'],
	ChartSkeleton: ['sm', 'md', 'lg'],
	Checkbox: ['xs', 'sm', 'md', 'lg'],
	CheckboxSkeleton: ['xs', 'sm', 'md', 'lg'],
	Code: ['sm', 'md', 'lg'],
	ColorPanel: ['xs', 'sm', 'md', 'lg'],
	ColorPanelSkeleton: ['xs', 'sm', 'md', 'lg'],
	ColorPicker: ['xs', 'sm', 'md', 'lg'],
	Combobox: ['xs', 'sm', 'md', 'lg'],
	CommandPaletteShortcut: ['sm', 'md', 'lg'],
	Control: ['xs', 'sm', 'md', 'lg'],
	ControlSkeleton: ['xs', 'sm', 'md', 'lg'],
	CopyButton: ['xs', 'sm', 'md', 'lg'],
	CreditCardInput: ['xs', 'sm', 'md', 'lg'],
	CreditCardInputCvv: ['xs', 'sm', 'md', 'lg'],
	CreditCardInputExpiry: ['xs', 'sm', 'md', 'lg'],
	CurrencyInput: ['xs', 'sm', 'md', 'lg'],
	DateInput: ['xs', 'sm', 'md', 'lg'],
	DatePicker: ['xs', 'sm', 'md', 'lg'],
	Drawer: ['sm', 'md', 'lg'],
	DrawerStatic: ['sm', 'md', 'lg'],
	FileUploadButton: ['xs', 'sm', 'md', 'lg'],
	FileUploadInput: ['xs', 'sm', 'md', 'lg'],
	Grid: ['sm', 'md', 'lg'],
	Group: ['xs', 'sm', 'md', 'lg'],
	Heading: ['sm', 'md', 'lg'],
	HeadingSkeleton: ['sm', 'md', 'lg'],
	HoldButton: ['xs', 'sm', 'md', 'lg'],
	Icon: ['xs', 'sm', 'md', 'lg'],
	Input: ['xs', 'sm', 'md', 'lg'],
	Kbd: ['sm', 'md', 'lg'],
	Listbox: ['xs', 'sm', 'md', 'lg'],
	LoadingDots: ['xs', 'sm', 'md', 'lg'],
	LoadingSpinner: ['xs', 'sm', 'md', 'lg'],
	MaskInput: ['xs', 'sm', 'md', 'lg'],
	Menu: ['sm', 'md', 'lg'],
	MenuShortcut: ['sm', 'md', 'lg'],
	NumberInput: ['xs', 'sm', 'md', 'lg'],
	PaginationNext: ['xs', 'sm', 'md', 'lg'],
	PaginationPrevious: ['xs', 'sm', 'md', 'lg'],
	PasswordConfirmNew: ['xs', 'sm', 'md', 'lg'],
	PasswordConfirmRepeat: ['xs', 'sm', 'md', 'lg'],
	PasswordInput: ['xs', 'sm', 'md', 'lg'],
	PivotTable: ['sm', 'md', 'lg'],
	PopoverContent: ['sm', 'md', 'lg'],
	ProgressBar: ['sm', 'md', 'lg'],
	ProgressBarSkeleton: ['sm', 'md', 'lg'],
	ProgressGauge: ['sm', 'md', 'lg'],
	ProgressGaugeSkeleton: ['sm', 'md', 'lg'],
	Radio: ['xs', 'sm', 'md', 'lg'],
	RadioSkeleton: ['xs', 'sm', 'md', 'lg'],
	RangeSlider: ['xs', 'sm', 'md', 'lg'],
	Rating: ['xs', 'sm', 'md', 'lg'],
	RatingSkeleton: ['xs', 'sm', 'md', 'lg'],
	SearchInput: ['xs', 'sm', 'md', 'lg'],
	Segment: ['sm', 'md', 'lg'],
	SegmentSkeleton: ['sm', 'md', 'lg'],
	Select: ['xs', 'sm', 'md', 'lg'],
	SidebarItem: ['sm', 'md', 'lg'],
	SidebarSkeleton: ['sm', 'md', 'lg'],
	Slider: ['xs', 'sm', 'md', 'lg'],
	SliderSkeleton: ['xs', 'sm', 'md', 'lg'],
	Sparkline: ['sm', 'md', 'lg'],
	SparklineSkeleton: ['sm', 'md', 'lg'],
	StatSkeleton: ['sm', 'md', 'lg'],
	StatValue: ['sm', 'md', 'lg'],
	StatValueSkeleton: ['sm', 'md', 'lg'],
	StatusDot: ['xs', 'sm', 'md', 'lg', 'xl'],
	Swatch: ['xs', 'sm', 'md', 'lg', 'xl'],
	Switch: ['xs', 'sm', 'md', 'lg'],
	SwitchSkeleton: ['xs', 'sm', 'md', 'lg'],
	TabListSkeleton: ['sm', 'md', 'lg'],
	Table: ['sm', 'md', 'lg'],
	Tabs: ['sm', 'md', 'lg'],
	TagInput: ['xs', 'sm', 'md', 'lg'],
	Text: ['xs', 'sm', 'md', 'lg'],
	TextSkeleton: ['xs', 'sm', 'md', 'lg'],
	Textarea: ['xs', 'sm', 'md', 'lg'],
	TextareaSkeleton: ['xs', 'sm', 'md', 'lg'],
	ToggleIconButton: ['xs', 'sm', 'md', 'lg'],
	ToggleIconButtonSkeleton: ['xs', 'sm', 'md', 'lg'],
	TooltipContent: ['sm', 'md', 'lg'],
	Tree: ['xs', 'sm', 'md', 'lg'],
	TreeSkeleton: ['xs', 'sm', 'md', 'lg'],
} as const satisfies Record<string, readonly DensityStep[]>

/** The name of a component with a `size` axis. */
export type SizedComponent = keyof typeof SIZE_AXES
