import type { DensityStep } from '../../core/density'

// The `size` axes of the documented components: each component whose `size`
// prop takes density steps, with the steps that the prop offers.
// `src/docs/__tests__/size-axes.test.ts` holds this list equal to the API data
// of the docs plugin, so a new axis or a changed axis must come here. The
// distinct-steps gate (`browser/geometry/size-steps.test.tsx`) renders each
// step of each axis.

/** The steps that the `size` prop of each documented component offers. */
export const SIZE_AXES = {
	AddressInput: ['sm', 'md', 'lg'],
	Avatar: ['sm', 'md', 'lg'],
	AvatarGroup: ['sm', 'md', 'lg'],
	AvatarSkeleton: ['sm', 'md', 'lg'],
	Badge: ['xs', 'sm', 'md', 'lg'],
	BadgeSkeleton: ['xs', 'sm', 'md', 'lg'],
	Button: ['xs', 'sm', 'md', 'lg'],
	ButtonSkeleton: ['xs', 'sm', 'md', 'lg'],
	Calendar: ['sm', 'md', 'lg'],
	CalendarRange: ['sm', 'md', 'lg'],
	CalendarSkeleton: ['sm', 'md', 'lg'],
	Card: ['sm', 'md', 'lg'],
	CardTitle: ['sm', 'md', 'lg'],
	ChartSkeleton: ['sm', 'md', 'lg'],
	Checkbox: ['sm', 'md', 'lg'],
	CheckboxSkeleton: ['sm', 'md', 'lg'],
	Code: ['sm', 'md', 'lg'],
	CodeBlock: ['sm', 'md', 'lg'],
	ColorPanel: ['sm', 'md', 'lg'],
	ColorPanelSkeleton: ['sm', 'md', 'lg'],
	ColorPicker: ['sm', 'md', 'lg'],
	ColorPickerSkeleton: ['sm', 'md', 'lg'],
	Combobox: ['sm', 'md', 'lg'],
	CommandPaletteClose: ['xs', 'sm', 'md', 'lg'],
	CommandPaletteShortcut: ['sm', 'md', 'lg'],
	Control: ['sm', 'md', 'lg'],
	ControlSkeleton: ['sm', 'md', 'lg'],
	CopyButton: ['xs', 'sm', 'md', 'lg'],
	CreditCardInput: ['sm', 'md', 'lg'],
	CreditCardInputCvv: ['sm', 'md', 'lg'],
	CreditCardInputExpiry: ['sm', 'md', 'lg'],
	CurrencyInput: ['sm', 'md', 'lg'],
	DateInput: ['sm', 'md', 'lg'],
	DatePicker: ['sm', 'md', 'lg'],
	DatePickerSkeleton: ['sm', 'md', 'lg'],
	DrawerPanel: ['sm', 'md', 'lg'],
	FileUploadButton: ['xs', 'sm', 'md', 'lg'],
	FileUploadInput: ['sm', 'md', 'lg'],
	Grid: ['sm', 'md', 'lg'],
	Group: ['xs', 'sm', 'md', 'lg'],
	Heading: ['sm', 'md', 'lg'],
	HeadingSkeleton: ['sm', 'md', 'lg'],
	HoldButton: ['xs', 'sm', 'md', 'lg'],
	Icon: ['xs', 'sm', 'md', 'lg'],
	Input: ['sm', 'md', 'lg'],
	Kbd: ['sm', 'md', 'lg'],
	Listbox: ['sm', 'md', 'lg'],
	LoadingDots: ['xs', 'sm', 'md', 'lg'],
	LoadingSpinner: ['xs', 'sm', 'md', 'lg'],
	MaskInput: ['sm', 'md', 'lg'],
	Menu: ['sm', 'md', 'lg'],
	MenuShortcut: ['sm', 'md', 'lg'],
	NumberInput: ['sm', 'md', 'lg'],
	PaginationNext: ['xs', 'sm', 'md', 'lg'],
	PaginationPrevious: ['xs', 'sm', 'md', 'lg'],
	PasswordConfirmNew: ['sm', 'md', 'lg'],
	PasswordConfirmRepeat: ['sm', 'md', 'lg'],
	PasswordInput: ['sm', 'md', 'lg'],
	PivotTable: ['sm', 'md', 'lg'],
	PopoverContent: ['sm', 'md', 'lg'],
	ProgressBar: ['sm', 'md', 'lg'],
	ProgressBarSkeleton: ['sm', 'md', 'lg'],
	ProgressGauge: ['sm', 'md', 'lg'],
	ProgressGaugeSkeleton: ['sm', 'md', 'lg'],
	Radio: ['sm', 'md', 'lg'],
	RadioSkeleton: ['sm', 'md', 'lg'],
	RangeSlider: ['sm', 'md', 'lg'],
	Rating: ['sm', 'md', 'lg'],
	RatingSkeleton: ['sm', 'md', 'lg'],
	SearchInput: ['sm', 'md', 'lg'],
	Segment: ['sm', 'md', 'lg'],
	SegmentSkeleton: ['sm', 'md', 'lg'],
	Select: ['sm', 'md', 'lg'],
	SidebarItem: ['sm', 'md', 'lg'],
	SidebarSkeleton: ['sm', 'md', 'lg'],
	Slider: ['sm', 'md', 'lg'],
	SliderSkeleton: ['sm', 'md', 'lg'],
	Sparkline: ['sm', 'md', 'lg'],
	SparklineSkeleton: ['sm', 'md', 'lg'],
	StatSkeleton: ['sm', 'md', 'lg'],
	StatValue: ['sm', 'md', 'lg'],
	StatValueSkeleton: ['sm', 'md', 'lg'],
	StatusDot: ['xs', 'sm', 'md', 'lg', 'xl'],
	Swatch: ['xs', 'sm', 'md', 'lg', 'xl'],
	Switch: ['sm', 'md', 'lg'],
	SwitchSkeleton: ['sm', 'md', 'lg'],
	TabListSkeleton: ['sm', 'md', 'lg'],
	Table: ['sm', 'md', 'lg'],
	Tabs: ['sm', 'md', 'lg'],
	TagInput: ['sm', 'md', 'lg'],
	Text: ['xs', 'sm', 'md', 'lg'],
	TextSkeleton: ['xs', 'sm', 'md', 'lg'],
	Textarea: ['sm', 'md', 'lg'],
	TextareaSkeleton: ['sm', 'md', 'lg'],
	ToggleIconButton: ['xs', 'sm', 'md', 'lg'],
	ToggleIconButtonSkeleton: ['xs', 'sm', 'md', 'lg'],
	TooltipContent: ['sm', 'md', 'lg'],
	Tree: ['xs', 'sm', 'md', 'lg'],
	TreeSkeleton: ['xs', 'sm', 'md', 'lg'],
} as const satisfies Record<string, readonly DensityStep[]>

/** The name of a component with a `size` axis. */
export type SizedComponent = keyof typeof SIZE_AXES
