export {
	SidebarLayout,
	SidebarLayoutBody,
	type SidebarLayoutBodyProps,
	SidebarLayoutFooter,
	type SidebarLayoutFooterProps,
	SidebarLayoutHeader,
	type SidebarLayoutHeaderProps,
	type SidebarLayoutProps,
} from './component'
export {
	type SidebarBodyVariants,
	type SidebarContentVariants,
	type SidebarContentWrapperVariants,
	type SidebarFooterVariants,
	type SidebarHeaderVariants,
	type SidebarLayoutVariants,
	type SidebarPanelVariants,
	sidebarBodyVariants,
	sidebarContentVariants,
	sidebarContentWrapperVariants,
	sidebarFooterVariants,
	sidebarHeaderVariants,
	sidebarLayoutVariants,
	sidebarPanelVariants,
} from './variants'
