import { defineConfig } from 'tsup'

export default defineConfig({
	entry: {
		index: 'src/index.ts',
		core: 'src/core/index.ts',
		recipes: 'src/recipes/index.ts',
		hooks: 'src/hooks/index.ts',
		primitives: 'src/primitives/index.ts',
		alert: 'src/components/alert/index.ts',
		avatar: 'src/components/avatar/index.ts',
		badge: 'src/components/badge/index.ts',
		button: 'src/components/button/index.ts',
		checkbox: 'src/components/checkbox/index.ts',
		combobox: 'src/components/combobox/index.ts',
		'description-list': 'src/components/description-list/index.ts',
		dialog: 'src/components/dialog/index.ts',
		divider: 'src/components/divider/index.ts',
		dropdown: 'src/components/dropdown/index.ts',
		fieldset: 'src/components/fieldset/index.ts',
		heading: 'src/components/heading/index.ts',
		input: 'src/components/input/index.ts',
		listbox: 'src/components/listbox/index.ts',
		navbar: 'src/components/navbar/index.ts',
		pagination: 'src/components/pagination/index.ts',
		radio: 'src/components/radio/index.ts',
		select: 'src/components/select/index.ts',
		sheet: 'src/components/sheet/index.ts',
		sidebar: 'src/components/sidebar/index.ts',
		'sidebar-layout': 'src/components/sidebar-layout/index.ts',
		'stacked-layout': 'src/components/stacked-layout/index.ts',
		switch: 'src/components/switch/index.ts',
		table: 'src/components/table/index.ts',
		text: 'src/components/text/index.ts',
		textarea: 'src/components/textarea/index.ts',
	},
	format: ['esm'],
	target: 'node22',
	outDir: 'dist',
	clean: true,
	dts: true,
	sourcemap: true,
	splitting: false,
})
